# -*- coding: utf-8 -*-
"""final27

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbuqNqvLr37nAPs2grfFJwDXsMTtL-_B
"""

randomNum = random(1,10)
guessNum=int(input("ทายตัวเลขระหว่าง 1-10 : "))
if guessNum = randomNum:
  print("ถูกต้อง คุณชนะ")
else:
  print("ผิด คำตอบคือ" , randomNum)